<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>no.nav.soknad.arkivering</groupId>
		<artifactId>archiving-system-tests</artifactId>
		<version>1.1.0</version>
	</parent>

	<artifactId>system-tests-clients</artifactId>
	<name>${project.artifactId}</name>
	<description>Clients used by system-tests</description>


	<dependencies>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
			<version>${springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webflux</artifactId>
			<version>${springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-stdlib</artifactId>
			<version>${kotlin.version}</version>
		</dependency>

		<dependency>
			<groupId>no.nav.soknad.innsending</groupId>
			<artifactId>innsending-api</artifactId>
			<version>19753d3-prod</version>
			<classifier>openapi-spec</classifier>
			<type>zip</type>
		</dependency>

		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>${okhttp3.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-kotlin</artifactId>
			<version>${jackson.version}</version>
		</dependency>
	</dependencies>


	<build>
		<finalName>${project.artifactId}</finalName>
		<sourceDirectory>target/generated-sources/openapi</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>${maven-dependency-plugin.version}</version>
				<executions>
					<execution>
						<id>unpack-openapi-spec</id>
						<phase>generate-sources</phase>
						<goals><goal>unpack</goal></goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>no.nav.soknad.innsending</groupId>
									<artifactId>innsending-api</artifactId>
									<classifier>openapi-spec</classifier>
									<type>zip</type>
									<outputDirectory>${project.build.directory}/innsending-api-spec</outputDirectory>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${openapi-generator-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>Generate soknadsmottaker client</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/soknadsmottaker-api.yml</inputSpec>
							<output>target/generated-sources/openapi</output>
							<generatorName>kotlin</generatorName>
							<apiPackage>no.nav.soknad.arkivering.soknadsmottaker.api</apiPackage>
							<modelPackage>no.nav.soknad.arkivering.soknadsmottaker.model</modelPackage>
							<configOptions>
								<serializationLibrary>jackson</serializationLibrary>
								<omitGradlePluginVersions>true</omitGradlePluginVersions>
								<groupId>no.nav.soknad.arkivering</groupId>
								<artifactId>soknadsmottaker-client</artifactId>
								<packageName>no.nav.soknad.arkivering.soknadsmottaker</packageName>
							</configOptions>
						</configuration>
					</execution>

					<execution>
						<id>Generate innsending-api client</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.build.directory}/innsending-api-spec/innsending-api.yml</inputSpec>
							<output>target/generated-sources/openapi</output>
							<generatorName>kotlin</generatorName>
							<apiPackage>no.nav.soknad.arkivering.innsending.api</apiPackage>
							<modelPackage>no.nav.soknad.arkivering.innsending.model</modelPackage>
							<configOptions>
								<serializationLibrary>jackson</serializationLibrary>
								<omitGradlePluginVersions>true</omitGradlePluginVersions>
								<groupId>no.nav.soknad.arkivering</groupId>
								<artifactId>innsending-client</artifactId>
								<packageName>no.nav.soknad.arkivering.innsending</packageName>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>


			<plugin>
				<groupId>org.jetbrains.kotlin</groupId>
				<artifactId>kotlin-maven-plugin</artifactId>
				<version>${kotlin.version}</version>
				<executions>
					<execution>
						<id>compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<jvmTarget>${java.version}</jvmTarget>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>central</id>
			<url>https://repo1.maven.org/maven2</url>
		</repository>
		<repository>
			<id>openhtmltopdf</id>
			<url>https://github.com/openhtmltopdf/openhtmltopdf</url>
		</repository>
		<repository>
			<id>github</id>
			<name>GitHub felles Maven Packagesfor Navikt</name>
			<url>https://github-package-registry-mirror.gc.nav.no/cached/maven-release</url>
		</repository>
	</repositories>
</project>
