package no.nav.soknad.arkivering.utils

data class SoknadDef(
	val skjemanr: String,
	val tema: String,
	val tittel: String,
)

data class VedleggDef(
	val vedleggKode: String,
	val vedleggTittel: String,
)

val skjemaliste = listOf(
	SoknadDef("NAV 10-07.54", "HJE", "Søknad om servicehund"),
	SoknadDef("NAV 95-20.05", "RPO", "Skjema for tips om mulig misbruk av stønad"),
	SoknadDef("NAV 12-15.01", "UFO", "Søknad om barnetillegg for deg som har uføretrygd"),
	SoknadDef("NAV 54-00.11", "BID", "Søknad om sletting av bidragsgjeld"),
	SoknadDef("NAV 10-07.10", "HEL", "Søknad om ortopedisk hjelpemiddel"),
	SoknadDef("NAV 10-07.57", "HEL", "Søknad om stønad til parykk"),
	SoknadDef("NAV 10-07.09", "HJE", "Regning for lese- og sekretærhjelp for blinde og svaksynte"),
	SoknadDef("NAV 76-07.10", "OPP", "Registreringsskjema for tilskudd til utdanning"),
	SoknadDef("NAV 76-13.85", "TIL", "Refusjonskrav - mentor"),
	SoknadDef("NAV 76-13.03", "TIL", "Innsøk til Varig tilrettelagt arbeid (VTA)"),
	SoknadDef("NAV 10-06.06", "HJE", "Seksualteknisk hjelpemiddel"),
	SoknadDef("NAV 10-07.30", "HJE", "Søknad om lese- og sekretærhjelp for blinde og svaksynte"),
	SoknadDef("NAV 76-13.84", "TIL", "Registreringsskjema for tiltaksarrangører - Mentor"),
	SoknadDef("NAV 76-13.02", "TIL", "Avtale om oppstart av lønnstilskudd"),
	SoknadDef("NAV 08-30.01", "SYK", "Inntektsmelding for arbeidstakere"),
	SoknadDef(
		"NAV 09-35.01",
		"OMS",
		"Inntektsopplysninger for selvstendig næringsdrivende og/eller frilansere som skal ha omsorgs-, pleie- eller opplæringspenger"
	),
	SoknadDef("NAV 67-01.01", "GEN", "Søknad om lønnsgarantidekning - melding av lønnskrav m.v. til konkursboet"),
	SoknadDef("NAV 10-07.26", "HJE", "Søknad om tilskudd til apper og programvare"),
	SoknadDef("NAV 21-04.01", "PEN", "Innleggelse i aldershjem/sykehjem"),
	SoknadDef("NAV 25-16.03", "AAP", "Søknad om arbeidsavklaringspenger som sykepengeerstatning - Koronapandemien"),
	SoknadDef("NAV 25-16.02", "SYK", "Refusjonskrav - kompensasjon ved innreiseforbud"),
	SoknadDef("NAV 25-16.01", "SYK", "Søknad om kompensasjon ved innreiseforbud"),
	SoknadDef("NAV 36-13.02", "FUL", "Innsyn med fullmakt eller samtykke"),
	SoknadDef("NAV 36-13.01", "FUL", "Innsyn med hjemmel"),
	SoknadDef("NAV 00-01.01", "TSO", "Kjøreliste for godkjent bruk av egen bil"),
	SoknadDef("NAV 64-01.00", "SUP", "Supplerende stønad til ufør flyktning"),
	SoknadDef("NAV 10-07.59", "HEL", "Søknad om stønad til brystprotese eller spesialbrystholder"),
	SoknadDef(
		"NAV 10-07.61",
		"HEL",
		"Søknad om refusjon av betalt egenandel for fottøy, fotseng og høreapparat ved yrkesskade"
	),
	SoknadDef("NAV 10-07.58", "HEL", "Søknad om stønad til øyeprotese eller ansiktsprotese"),
	SoknadDef("NAV 64-21.00", "SUP", "Søknad om supplerende stønad til personer over 67 år"),
	SoknadDef("NAV 10-07.54", "HJE", "Søknad om servicehund"),
	SoknadDef("NAV 15-00.04", "ENF", "Søknad om stønad til skolepenger - enslig mor eller far"),
	SoknadDef("NAV 10-07.17", "BIL", "Søknad om refusjon av reiseutgifter i forbindelse med bilstønadsordningen"),
	SoknadDef("NAV 04-16.03", "DAG", "Søknad om gjenopptak av dagpenger"),
	SoknadDef("NAV 10-07.60", "HEL", "Søknad om stønad til alminnelig fottøy ved ulik fotstørrelse"),
	SoknadDef("NAV 10-07.19", "HJE", "Søknad om refusjon av reiseutgifter - tekniske hjelpemidler"),
	SoknadDef("NAV 54-00.07", "BID", "Svar på forhåndsvarsel i sak om barnebidrag (bidragspliktig)"),
	SoknadDef("NAV 54-00.08", "BID", "Søknadsskjema for bidragspliktig"),
	SoknadDef("NAV 00-10.01", "GEN", "Papirmeldekort"),
	SoknadDef("NAV 09-06.05", "OMS", "Søknad om flere omsorgsdager / melding om fordeling og overføring av dagene"),
	SoknadDef("NAV 00-01.00", "OPP", "Kjøreliste med tema Oppfølging - skal erstatte Oppfølging bistand"),
	SoknadDef("NAV 55-00.10", "BID", "Erklæring om farskap"),
	SoknadDef("NAV 95-20.20", "PEN", "Melding om midlertidig postadresse i NAV"),
	SoknadDef("NAV 10-07.20", "HJE", "Hjelp til vurdering og utprøving"),
	SoknadDef("NAV 42-02.11", "MED", "Bekreftelse på medlemskap etter trygdeavtalen med Quebec"),
	SoknadDef("NAV 16-01.05", "PEN", "Søknad om ytelser til tidligere familiepleier"),
	SoknadDef("NAV 10-07.24", "HJE", "Søknad om stønad til ekstrautgifter på folkehøyskole"),
	SoknadDef("NAV 08-09.08", "SYK", "Egenerklæring Sykepenger-EØS"),
	SoknadDef("NAV 54-00.04", "BID", "Svar på forhåndsvarsel i sak om barnebidrag"),
	SoknadDef("NAV 60-13.09", "FOS", "Melding om biinntekt før fratredelse"),
	SoknadDef("NAV 10-07.55", "HJE", "Søknad om stønad til grunnmønster og søm etter grunnmønster"),
	SoknadDef("NAV 34-00.15", "BAR", "Utbetaling av barnetrygd og/eller kontantstøtte i et annet EØS-land"),
	SoknadDef("NAV 60-13.13", "FOS", "Melding om inntekt - ventelønn"),
	SoknadDef("NAV 10-07.03", "HJE", "Søknad om hjelpemidler (for fagperson)"),
	SoknadDef("NAV 10-07.15", "HJE", "Søknad om dekning av utgifter til irislinser"),
	SoknadDef("NAV 06-04.04", "GRU", "Søknad om hjelpestønad"),
	SoknadDef("NAV 06-03.04", "GRU", "Søknad om grunnstønad"),
	SoknadDef("NAV 10-07.34", "HJE", "Tilskudd ved kjøp av briller til barn"),
	SoknadDef("NAV 10-07.87", "HJE", "Søknad om synshjelpemidler"),
	SoknadDef(
		"NAV 10-07.53",
		"HJE",
		"Søknad om dekning av ekstraordinære veterinærutgifter for førerhund eller servicehund"
	),
	SoknadDef("NAV 19-01.10", "PEN", "Endring av alderspensjon"),
	SoknadDef("NAV 14-05.08", "FOR", "Søknad om engangsstønad ved adopsjon"),
	SoknadDef("NAV 11-12.05", "AAP", "Søknad om reisestønad (AAP)"),
	SoknadDef("NAV 10-07.18", "HJE", "Søknad om stønad til tilpasningskurs"),
	SoknadDef("NAV 04-03.07", "DAG", "Egenerklæring - overdragelse av lønnskrav"),
	SoknadDef("NAV 10-07.08", "HJE", "Søknad om høreapparat / tinnitusmaskerer / tilleggsutstyr"),
	SoknadDef("NAV 08-14.01", "SYK", "Søknad om refusjon av reisetilskudd til arbeidsreiser"),
	SoknadDef(
		"NAV 17-09.01",
		"PEN",
		"Søknad om stønad til barnetilsyn på grunn av arbeid og stønad til skolepenger til gjenlevende ektefelle/partner/ samboer og til ugift familiepleier"
	),
	SoknadDef("NAV 10-07.06", "HJE", "Søknad om tolk til døve, døvblinde og hørselshemmede"),
	SoknadDef("NAV 13-00.21", "YRK", "Skadeforklaring ved arbeidsulykke"),
	SoknadDef("NAV 04-06.05", "DAG", "Søknad om å beholde dagpengene mens du tar utdanning eller opplæring"),
	SoknadDef("NAV 08-09.07", "SYK", "Søknad om å beholde sykepenger under opphold i utlandet"),
	SoknadDef("NAV 08-47.05", "SYK", "Krav om sykepenger – midlertidig ute av inntektsgivende arbeid"),
	SoknadDef("NAV 08-09.06", "SYK", "Egenerklæring for utenlandske sykemeldinger"),
	SoknadDef("NAV 10-07.33", "HJE", "Søknad om hjelpemidler (for privatperson)"),
	SoknadDef("NAV 13-17.05", "YRK", "Søknad om menerstatning"),
	SoknadDef("NAV 10-07.04", "HJE", "Fullmakt i forbindelse med søknad om tekniske hjelpemidler"),
	SoknadDef("NAV 11-13.09", "AAP", "Søknad om arbeidsavklaringspenger under etablering av egen virksomhet (oppstartfase)"),
	SoknadDef("NAV 53-00.05", "BID", "Søknad om ektefellebidrag"),
	SoknadDef(
		"NAV 11-13.08",
		"AAP",
		"Søknad om arbeidsavklaringspenger under etablering av egen virksomhet (utviklingsfase)"
	),
	SoknadDef("NAV 19-01.05", "PEN", "Søknad om alderspensjon"),
	SoknadDef("NAV 31-00.02", "PEN", "Krigspensjoneringen - Krav om invalidepensjon"),
	SoknadDef("NAV 14-05.07", "FOR", "Søknad om engangsstønad ved fødsel"),
	SoknadDef("NAV 31-00.03", "PEN", "Krigspensjoneringen - Krav om etterlattepensjon"),
	SoknadDef("NAV 12-09.01", "UFO", "Søknad om endret inntektsgrense"),
	SoknadDef("NAV 10-07.50", "HJE", "Søknad om førerhund"),
	SoknadDef("NAV 02-08.07", "MED", "Søknad om avklaring av trygdetilhørighet under opphold i EØS eller Sveits"),
	SoknadDef(
		"NAV 08-35.01",
		"SYK",
		"Inntektsopplysninger for selvstendig næringsdrivende og/eller frilansere som skal ha sykepenger"
	),
	SoknadDef("NAV 04-06.08", "DAG", "Søknad om dagpenger under etablering av egen virksomhet"),
	SoknadDef(
		"NAV 10-07.16",
		"HEL",
		"Søknad om refusjon av reiseutgifter knyttet til ortopediske hjelpemidler, parykk, tilpasningskurs, folkehøyskole, grunnmønster eller brystprotese"
	),
	SoknadDef("NAV 12-14.01", "UFO", "Melding om inntektsendring når du har uføretrygd"),
	SoknadDef("NAV 10-07.23", "HJE", "Behov for hjelpemidler knyttet til individuell plan"),
	SoknadDef("NAV 18-04.05", "PEN", "Søknad om barnepensjon etter fylte 18 år"),
	SoknadDef("NAV 54-00.13", "BID", "Søknad om bidrag til særlige utgifter"),
	SoknadDef("NAV 76-13.45", "IND", "Søknad om tiltakspenger"),
	SoknadDef("NAV 21-03.05", "PEN", "Leveattest"),
	SoknadDef("NAV 57-00.08", "BID", "Skjema for oppfostringsbidrag etter lov om barneverntjenester - for bidragspliktig"),
	SoknadDef("NAV 55-44.01", "BID", "Fordeling av barns reisekostnader ved samvær"),
	SoknadDef(
		"NAV 13-13.05",
		"YRK",
		"Søknad fra selvstendig næringsdrivende og frilansere om frivillig opptak i NAVs yrkesskadeordning"
	),
	SoknadDef(
		"NAV 62-00.16",
		"PEN",
		"Opplysninger fra arbeidstaker til NAV ved søknad om avtalefestet pensjon (AFP) fra Statens pensjonskasse"
	),
	SoknadDef("NAV 17-01.06", "EYO", "Søknad om omstillingsstønad"),
	SoknadDef("NAV 04-02.05", "DAG", "Søknad om attest PD U1/N-301 til bruk ved overføring av dagpengerettigheter"),
	SoknadDef("NAV 02-08.05", "MED", "Søknad om medlemskap i folketrygden under opphold utenfor EØS"),
	SoknadDef("NAV 14-05.09", "FOR", "Søknad om foreldrepenger ved fødsel"),
	SoknadDef("NAV 17-15.01", "PEN", "Søknad om ytelser til tidligere familiepleier"),
	SoknadDef("NAV 04-02.01", "DAG", "Søknad om utstedelse av attest PD U2"),
	SoknadDef("NAV 02-07.05", "MED", "Søknad om frivillig medlemskap i folketrygden under opphold i Norge"),
	SoknadDef("NAV 14-05.06", "FOR", "Søknad om foreldrepenger ved adopsjon"),
	SoknadDef("NAV 10-07.31", "HJE", "Bytte av hjelpemiddel"),
	SoknadDef("NAV 34-00.08", "KON", "Søknad om kontantstøtte til småbarnsforeldre"),
	SoknadDef("NAV 33-00.09", "BAR", "Søknad om utvidet barnetrygd"),
	SoknadDef("NAV 10-07.48", "BIL", "Gjeldsbrev ved stønad til kjøp av motorkjøretøy i gruppe 1"),
	SoknadDef("NAV 55-85.01", "FAR", "Søknad om anerkjennelse av farskap eller medmorskap"),
	SoknadDef("NAV 07-02.08", "GRA", "Søknad om gravferdsstønad og båretransport"),
	SoknadDef("NAV 06-07.02", "GRU", "Svar på brev om vurdering av hjelpestønad"),
	SoknadDef("NAV 06-07.01", "GRU", "Svar på brev om vurdering av grunnstønad"),
	SoknadDef("NAV 76-13.54", "TIL", "Refusjonskrav – Varig tilrettelagt arbeid (VTA) i ordinær virksomhet"),
	SoknadDef("NAV 76-13.72", "TIL", "Søknad og avtale om tiltaksplass for varig tilrettelagt arbeid i ordinær virksomhet"),
	SoknadDef("NAV 76-13.88", "TIL", "Søknad om inkluderingstilskudd"),
	SoknadDef("NAV 21-04.05", "GEN", "Melding til NAV om elevs fravær fra skolen som kan skyldes utenlandsopphold"),
	SoknadDef("NAV 12-06.09", "UFO", "Inntektsskjema for gårdbrukere - uføretrygd"),
	SoknadDef("NAV 12-06.07", "UFO", "Inntektsskjema for næringsdrivende og ansatt i eget aksjeselskap - uføretrygd"),
	SoknadDef("NAV 04-02.03", "DAG", "Bekreftelse på ansettelsesforhold"),
	SoknadDef("NAV 04-06.10", "DAG", "Næringsfaglig vurdering av etableringsplaner"),
	SoknadDef("NAV 12-06.06", "UFO", "Inntektsskjema for arbeidstakere - uføretrygd"),
	SoknadDef("NAV 25-02.01", "OPP", "Oppfølgingsplan ved sykmelding"),
	SoknadDef("NAV 02-08.06", "MED", "Skjema for arbeidsgiver – bekreftelse på utsending utenfor EØS"),
	SoknadDef("NAV 10-07.13", "HEL", "Innsending av søknad om fornyelse av ortopedisk hjelpemiddel"),
	SoknadDef("NAV 04-08.04", "DAG", "Bekreftelse på arbeidsforhold og permittering"),
	SoknadDef("NAV 08-54.05", "GEN", "Melding om institusjonsopphold"),
	SoknadDef("NAV 76-07.15", "TIL", "Avtale om egenfinansiering av utdanning"),
	SoknadDef("NAV 55-00.63", "BID", "Avtale om barnebidrag for barn over 18 år"),
	SoknadDef("NAV 55-00.60", "BID", "Avtale om barnebidrag"),
	SoknadDef("NAV 10-07.80", "HJE", "Bekreftelse på utlån og tildeling av høreapparat / tinnitusmaskerer / tilleggsutstyr"),
	SoknadDef("NAV 11-03.07", "AAP", "Søknad om å beholde arbeidsavklaringspenger under opphold i utlandet "),
	SoknadDef("NAV 10-07.42", "BIL", "Legeerklæring for motorkjøretøy"),
	SoknadDef(
		"NAV 10-07.43",
		"BIL",
		"Tilleggsskjema fra ergo- eller fysioterapeut i forbindelse med søknad om motorkjøretøy og spesialutstyr / tilpasning"
	),
	SoknadDef("NAV 10-07.05", "HJE", "Bestilling av tekniske hjelpemidler"),
	SoknadDef(
		"NAV 08-20.12",
		"SYK",
		"Krav fra arbeidsgiveren om refusjon av sykepenger  utbetalt til en arbeidstaker som er unntatt fra  bestemmelsene om arbeidsgiveransvar"
	),
	SoknadDef("NAV 08-07.08", "OPP", "Legeerklæring ved arbeidsuførhet"),
	SoknadDef(
		"NAV 08-30.02",
		"TRK",
		"Trekkopplysninger for arbeidstaker som skal ha sykepenger, foreldrepenger, svangerskapspenger, pleie-/opplæringspenger og omsorgspenger"
	),
	SoknadDef("NAV 70-02.05", "GEN", "Melding om opphold på helseinstitusjon"),
	SoknadDef("NAV 08-07.04", "SYK", "Vurdering av arbeidsmulighet / Sykmelding"),
	SoknadDef("NAV 04-13.01", "DAG", "Egenerklæringsskjema for fastsettelse av grensearbeiderstatus"),
	SoknadDef("NAV 10-07.90", "HJE", "Godkjenningsskjema for montering av hjelpemidler på bad"),
	SoknadDef("NAV 45-12.00", "UFO", "EØS - detaljert legeerklæring - EF forordning 987/2009, artikkel 87"),
	SoknadDef(
		"NAV 02-08.09",
		"MED",
		"Søknad om å være omfattet av norsk trygdelovgivning under opphold i et annet EØS-land eller Sveits"
	),
	SoknadDef("NAV 60-13.05", "VEN", "Søknad om ventelønn for ny periode"),
	SoknadDef("NAV 70-02.03", "PEN", "Innleggelse i aldershjem/sykehjem"),
	SoknadDef("NAV 21-04.02", "GEN", "Melding om opphold på helseinstitusjon"),
	SoknadDef(
		"NAV 08-21.15",
		"FOS",
		"Forsikring mot ansvar for sykepenger i arbeidsgiverperioden for små bedrifter - krav om refusjon"
	),
	SoknadDef("NAV 12-06.15", "PEN", "Bekreftelse på vedtak om uføretrygd for utstedelse av honnørkort"),
	SoknadDef("NAV 76-13.95", "TIL", "Underveis- og sluttevaluering av AMO-KURS"),
	SoknadDef("NAV 06-03.11", "HJE", "Hjelpeskjema - Ekstrautgifter til slitasje på klær og sengetøy"),
	SoknadDef("NAV 76-13.16", "TIL", "Fremmøteliste ved deltakelse på arbeidstrening"),
	SoknadDef("NAV 02-08.08", "MED", "Skjema for arbeidsgiver – bekreftelse på utsending i EØS eller Sveits"),
	SoknadDef(
		"NAV 09-06.09",
		"OMS",
		"Legeerklæring ved søknad om ekstra omsorgsdager for kronisk sykt eller funksjonshemmet barn"
	),
	SoknadDef("NAV 03-16.01", "PEN", "Søknad om godskriving av omsorgsopptjening"),
	SoknadDef("NAV 08-21.05", "FOS", "Forsikring mot ansvar for sykepenger i arbeidsgiverperioden for små bedrifter"),
	SoknadDef("NAV 23-05.05", "STO", "Terminoppgave for produktavgift til folketrygden")
)

val vedleggsliste: List<VedleggDef> = listOf(
	VedleggDef("L8", "Uttalelse fra fagpersonell"),
	VedleggDef("L9", "Legeerklæring"),
	VedleggDef("W2", "Vedtak eller avtale om bidrag"),
	VedleggDef("CC", "Avtale"),
	VedleggDef("BJ", "Dokumentasjon på ekteskapsinngåelse"),
)
