version: '3.7'
services:

  kafka-broker:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: "privat-soknadInnsendt-v1-teamsoknad:1:1,privat-soknadInnsendt-processingEventLog-v1-teamsoknad:1:1,privat-soknadInnsendt-messages-v1-teamsoknad:1:1,privat-soknadInnsendt-endToEndTests-entities:1:1,privat-soknadInnsendt-endToEndTests-numberOfCalls:1:1,privat-soknadInnsendt-endToEndTests-numberOfEntities:1:1,privat-soknadInnsendt-metrics-v1-teamsoknad:1:1"
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      # For more details see https://rmoff.net/2018/08/02/kafka-listeners-explained/
      KAFKA_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://kafka-broker:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - kafka-zookeeper

  kafka-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: kafka-schema-registry
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker:29092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - kafka-zookeeper
      - kafka-broker

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soknadsfillager
    ports:
      - 5432:5432


  arkiv-mock:
    build: arkiv-mock
    ports:
      - 8092:8092
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092

  soknadsmottaker:
    build: ../soknadsmottaker
    ports:
      - 8090:8090
    depends_on:
      - kafka-broker
      - kafka-schema-registry
    environment:
     - SPRING_PROFILES_ACTIVE=docker

  soknadsarkiverer:
    build: ../soknadsarkiverer
    ports:
      - 8091:8091
    depends_on:
      - kafka-broker
      - kafka-schema-registry
      - soknadsfillager
      - arkiv-mock
    environment:
     - SPRING_PROFILES_ACTIVE=test
     - FILESTORAGE_HOST=http://soknadsfillager:9042
     - JOARK_HOST=http://arkiv-mock:8092
     - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092
     - SCHEMA_REGISTRY_URL=http://kafka-schema-registry:8081

  soknadsfillager:
    build: ../soknadsfillager
    ports:
      - 9042:9042
    depends_on:
      - postgres
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - DATABASE_HOST=postgres
     - DATABASE_PORT=5432
     - DATABASE_NAME=soknadsfillager
     - DATABASE_USERNAME=postgres
     - DATABASE_PASSWORD=postgres
     - APPLICATION_PROFILE=docker
