version: '3.8'
services:

  kafka-broker:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "privat-soknadinnsending-v1-dev:1:1,privat-soknadinnsending-processingeventlog-v1-dev:1:1,privat-soknadinnsending-messages-v1-dev:1:1,privat-soknadinnsending-metrics-v1-dev:1:1,privat-soknadinnsending-systemtests-entities:1:1,privat-soknadinnsending-systemtests-numberofcalls:1:1,min-side.aapen-brukernotifikasjon-done-v1:1:1,min-side.aapen-brukernotifikasjon-beskjed-v1:1:1,min-side.aapen-brukernotifikasjon-oppgave-v1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      # For more details see https://rmoff.net/2018/08/02/kafka-listeners-explained/
      KAFKA_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://kafka-broker:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - kafka-zookeeper

  kafka-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: kafka-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker:29092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - kafka-zookeeper
      - kafka-broker

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"


  soknadsmottaker:
    build: ../soknadsmottaker
    ports:
      - "8090:8090"
    depends_on:
      - kafka-broker
      - kafka-schema-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NAIS_NAMESPACE=team-soknad
      - KAFKA_SECURITY=false
      - KAFKA_SCHEMA_REGISTRY=http://kafka-schema-registry:8081
      - KAFKA_BROKERS=kafka-broker:29092
      - INNSENDING_USERNAME=innsending
      - INNSENDING_PASSWORD=password

  soknadsfillager:
    build: ../soknadsfillager
    ports:
      - "9042:9042"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
      - DATABASE_DATABASE=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - INNSENDING_USERNAME=sender
      - INNSENDING_PASSWORD=password

  arkiv-mock:
    build: ../arkiv-mock
    ports:
      - "8092:8092"
    depends_on:
      - kafka-broker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_SECURITY=false
      - KAFKA_BROKERS=kafka-broker:29092

  soknadsarkiverer:
    build: ../soknadsarkiverer
    ports:
      - "8091:8091"
    depends_on:
      - kafka-broker
      - kafka-schema-registry
      - soknadsfillager
      - arkiv-mock
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - FILESTORAGE_HOST=http://soknadsfillager:9042
      - JOARK_HOST=http://arkiv-mock:8092
      - KAFKA_BROKERS=kafka-broker:29092
      - KAFKA_SCHEMA_REGISTRY=http://kafka-schema-registry:8081
      - BOOTSTRAPPING_TIMEOUT=1
