version: '3.7'
services:

  kafka-broker:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_CREATE_TOPICS: "privat-soknadInnsendt-sendsoknad-v1-q0:1:1"
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      # For more details see https://rmoff.net/2018/08/02/kafka-listeners-explained/
      KAFKA_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://kafka-broker:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - 'kafka-zookeeper'

  kafka-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'


  mock-mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  joark-mock:
    build: ../joark-mock
    ports:
      - 8092:8092
    depends_on:
      - mock-mongodb
    environment:
     - SPRING_PROFILES_ACTIVE=docker

  soknadsmottaker:
    build: ../soknadsmottaker
    ports:
      - 8090:8090
    depends_on:
      - kafka-broker
      - joark-mock
    environment:
     - SPRING_PROFILES_ACTIVE=docker

  soknadsarkiverer:
    build: ../soknadsarkiverer
    ports:
      - 8091:8091
    depends_on:
      - kafka-broker
      - joark-mock
    environment:
     - SPRING_PROFILES_ACTIVE=docker
