apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: team-soknad
  name: innsending-system-tests
  namespace: team-soknad
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "320M"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  schedule: "0 6 * * MON" # Every Monday at 6 am
#  schedule: "0 */5 * * *" # Every five hours
#  schedule: "30 * * * *"  # Once an hour, at 30 past
#  schedule: "*/10 * * * *"  # Every 10 minutes
  accessPolicy:
    outbound:
      rules:
        - application: soknadsmottaker-loadtests
        - application: innsending-api-loadtests
        - application: archive-mock
  env:
    - name: KAFKA_SECURITY
      value: "TRUE"
    - name: KAFKA_MAIN_TOPIC
      value: team-soknad.privat-soknadinnsending-v1-loadtests
    - name: KAFKA_PROCESSING_TOPIC
      value: team-soknad.privat-soknadinnsending-processingeventlog-v1-loadtests
    - name: KAFKA_METRICS_TOPIC
      value: team-soknad.privat-soknadinnsending-metrics-v1-loadtests
    - name: KAFKA_MESSAGE_TOPIC
      value: team-soknad.privat-soknadinnsending-messages-v1-loadtests
    - name: KAFKA_ARKIVERINGSTILBAKEMELDING_TOPIC
      value: team-soknad.privat-soknadinnsending-arkiveringstilbakemeldinger-v1-loadtests
    - name: KAFKA_ENTITIES_TOPIC
      value: team-soknad.privat-soknadinnsending-systemtests-entities
    - name: KAFKA_NUMBER_OF_CALLS_TOPIC
      value: team-soknad.privat-soknadinnsending-systemtests-numberofcalls
    - name: SOKNADSMOTTAKER_URL
      value: https://soknadsmottaker-gcp-loadtests.intern.dev.nav.no
    - name: INNSENDINGAPI_URL
      value: http://innsending-api-loadtests
    - name: ARKIVMOCK_URL
      value: https://arkiv-mock-gcp.intern.dev.nav.no

  image: {{image}}
  ttlSecondsAfterFinished: 3600
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 1024Mi

  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
    streams: true
