apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: team-soknad
  name: innsending-system-tests
  namespace: team-soknad
spec:
  schedule: "0 6 * * MON" # Every Monday at 6 am
  #  schedule: "0 */5 * * *" # Every five hours
  #  schedule: "30 * * * *"  # Once an hour, at 30 past

  accessPolicy:
    outbound:
      rules:
        - application: arkiv-mock
  envFrom:
    - secret: shared-innsending-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  env:
    - name: KAFKA_SECURITY
      value: "TRUE"
    - name: KAFKA_MAIN_TOPIC
      value: privat-soknadinnsending-v1-loadtests
    - name: KAFKA_PROCESSING_TOPIC
      value: privat-soknadinnsending-processingeventlog-v1-loadtests
    - name: KAFKA_METRICS_TOPIC
      value: privat-soknadinnsending-metrics-v1-loadtests
    - name: KAFKA_MESSAGE_TOPIC
      value: privat-soknadinnsending-messages-v1-loadtests
    - name: SOKNADSFILLAGER_URL
      value: https://soknadsfillager-gcp-loadtests.dev.intern.nav.no
    - name: SOKNADSMOTTAKER_URL
      value: https://soknadsmottaker-gcp-loadtests.dev.intern.nav.no

  image: {{image}}
  ttlSecondsAfterFinished: 3600
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 1024Mi

  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
    streams: true
