name: 'Checkout and build'
description: 'Checkout, compile and docker build component'
inputs:
  component_name:
    description: 'Name of component'
    required: true
  branch:
    description: 'Branch to check out'
    required: false
    default: "main"
  sub_directory:
    description: 'Directory to go to before building'
    required: false
    default: "."
  skip_tests:
    description: 'Whether tests should be skipped during build'
    required: false
    default: "true"
  run_docker_build:
    description: 'Whether docker build should be run'
    required: false
    default: "true"


runs:
  using: "composite"
  steps:
    - name: 'Checkout, compile and Docker Build'
      shell: bash
      run: |
        orig_path=$(pwd)
        if [ ! -d "${{ inputs.component_name }}" ]; then
          git clone https://github.com/navikt/${{ inputs.component_name }}.git
        fi
        cd ${{ inputs.component_name }}
        git checkout ${{ inputs.branch }}
        cd ${{ inputs.sub_directory }}

        TEST_PARAM=""
        if [[ ${{ inputs.skip_tests }} = "true" ]]; then
          TEST_PARAM="-DskipTests"
        fi

        mvn clean install $TEST_PARAM

        if [[ ${{ inputs.run_docker_build }} = "true" ]]; then
          APP_NAME=$(echo $(pwd) | rev | cut -f1 -d"/" | rev)
          TAG="archiving-infrastructure_${APP_NAME}:latest"
          docker build --tag $TAG .
          docker images
        fi
        cd "$orig_path"
