@startuml
actor       ExternalService
participant InnsendingApi
participant Soknadsmottaker
queue       Soknadinnsending
participant Soknadsarkiverer
queue       ProcessingEvents
queue       Arkiveringstilbakemeldinger
database    Joark
ExternalService  ->             InnsendingApi    : Create application (POST)
loop X times
    ExternalService  ->             InnsendingApi    : LagreFil (POST)
end
ExternalService  ->             InnsendingApi    : SendInnSoknad (POST)
InnsendingApi    ->             Soknadsmottaker  : Receive (POST)
Soknadsmottaker  ->             Soknadinnsending            : Queue
InnsendingApi    ->             ExternalService  : OK
Soknadinnsending            ->             Soknadsarkiverer : Queue
Soknadsarkiverer -[#0000FF]-//o ProcessingEvents : RECEIVED
Soknadsarkiverer -[#0000FF]-//o ProcessingEvents : STARTED
Soknadsarkiverer ->             InnsendingApi    : Request Files (GET)
InnsendingApi    ->             Soknadsarkiverer : File Results
Soknadsarkiverer ->             Joark            : Archive (POST)
Joark            ->             Soknadsarkiverer : Archive Response
Soknadsarkiverer -[#0000FF]-//o ProcessingEvents : ARCHIVED
Soknadsarkiverer -[#0000FF]-//o Arkiveringstilbakemeldinger            : Archiving: OK
Arkiveringstilbakemeldinger -> InnsendingApi    : Archiving: OK
Soknadsarkiverer -[#0000FF]-//o ProcessingEvents : FINISHED
@enduml
