name: Manually triggered build and run tests
run-name: Manual deploy to ${{ inputs.environment }} [${{ github.ref_name }}]
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'preprod'
        type: choice
        options:
          - none
          - preprod

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: 'Build the code for soknadsmottaker'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: soknadsmottaker

      - name: 'Build the code for soknadsfillager'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: soknadsfillager

      - name: 'Build the code for soknadsarkiverer'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: soknadsarkiverer

      - name: 'Build the code for arkiv-mock'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: arkiv-mock

      - name: 'Build and run the end-to-end-tests'
        run: mvn install --file system-tests/pom.xml
