name: Register load-tests cron-job on push
on:
  push:

env:
  docker_image: ghcr.io/${{ github.repository }}/innsending-system-tests:latest

jobs:
  build:
    name: Build tests, package tests in docker image and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Read/save .m2 cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn install --file system-tests/pom.xml -DskipTests
      - uses: docker/build-push-action@v3
        with:
          context: system-tests
          push: true
          tags: ${{ env.docker_image }}

  deploy-load-tests-cron-job:
    name: Deploy load-tests as a CronJob
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: system-tests/.nais/preprod-teamsoknad.yml
          VAR: image=${{ env.docker_image }}
